apiVersion: v1
kind: Service
metadata:
  name: apachephp
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080   # You can choose a port between 30000-32767
  selector:
    app: apachephp

