apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql-custom:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: mydb
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql

      # volumes:
      # - name: mysql-storage
      #   persistentVolumeClaim:
      #     claimName: mysql-pvc

      # for testing - use emptyDir
      volumes:
      - name: mysql-storage
        emptyDir: {}
